openapi: 3.0.0
info:
  title: AI Documentation Assistant POC API
  description: API for the AI Documentation Assistant proof of concept
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development server
paths:
  /api/posts:
    get:
      summary: Get all posts
      description: Retrieve all posts from the database
      operationId: getAllPosts
      tags:
        - posts
      responses:
        '200':
          description: List of posts retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the post
        title:
          type: string
          description: Title of the post
        subtitle:
          type: string
          description: Subtitle of the post
        content:
          type: string
          description: Content of the post
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the post was created
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the post was last updated
      required:
        - id
        - title
        - content

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
        errorCode:
          type: string
          description: Error code for programmatic handling
        timestamp:
          type: string
          format: date-time
          description: Timestamp when the error occurred
      required:
        - error
        - errorCode
        - timestamp
