name: AI Documentation Generator

on:
  pull_request:
    types: [ closed ]  # Only trigger when PR is closed
    branches: [ main ] # Only for PRs targeting main branch

jobs:
  generate-documentation:
    # Only run if the PR was actually merged (not just closed)
    if: github.event.pull_request.merged == true
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Needed to push to wiki
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for better git operations
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Configure Git
      run: |
        git config --global user.name "AI Documentation Bot"
        git config --global user.email "noreply@github.com"
        
    - name: Debug Git Information
      run: |
        echo "PR merged into main: ${{ github.event.pull_request.merge_commit_sha }}"
        echo "PR head commit: ${{ github.event.pull_request.head.sha }}"
        echo "Current commit: ${{ github.sha }}"
        echo "Git log:"
        git log --oneline -5
        echo "Git status:"
        git status
        echo "Changed files in this PR:"
        git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} || echo "Could not get PR diff"
        
    - name: Generate AI Documentation
      env:
        AI_API_KEY: ${{ secrets.AI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        python scripts/ai_doc_generator.py \
          --commit-sha ${{ github.event.pull_request.head.sha }} \
          --ai-provider anthropic