name: AI Documentation Generator

on:
  push:
    branches: [ main, master ]  # Trigger on pushes to main/master
  pull_request:
    types: [ closed ]  # Also trigger when PRs are merged
    branches: [ main, master ]

jobs:
  generate-documentation:
    # Only run on merged PRs or direct pushes to main
    if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Needed to push to wiki
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Fetch last 2 commits to get diff
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Configure Git
      run: |
        git config --global user.name "AI Documentation Bot"
        git config --global user.email "noreply@github.com"
        
    - name: Generate AI Documentation
      env:
        AI_API_KEY: ${{ secrets.AI_API_KEY }}  # or ANTHROPIC_API_KEY
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        python scripts/ai_doc_generator.py \
          --commit-sha ${{ github.sha }} \
          --ai-provider openai
          
    - name: Generate Documentation (Dry Run) on PR
      if: github.event_name == 'pull_request' && github.event.action != 'closed'
      env:
        AI_API_KEY: ${{ secrets.AI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        python scripts/ai_doc_generator.py \
          --commit-sha ${{ github.event.pull_request.head.sha }} \
          --ai-provider openai \
          --dry-run